// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXIThmo6oHAqlDAKO2wMb9ogkLRNug1s',
    appId: '1:283367837480:web:07863a7eb789508ef60a1d',
    messagingSenderId: '283367837480',
    projectId: 'mokumokuhazard',
    authDomain: 'mokumokuhazard.firebaseapp.com',
    storageBucket: 'mokumokuhazard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVMP3_rKOEmZd5Fcq2YRq26MtskWXia8',
    appId: '1:283367837480:android:0738c42ed0005de1f60a1d',
    messagingSenderId: '283367837480',
    projectId: 'mokumokuhazard',
    storageBucket: 'mokumokuhazard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiYSFco6wLuLOiMlCI4Z8MHutKcVwbWo',
    appId: '1:283367837480:ios:5916df8ca5f499caf60a1d',
    messagingSenderId: '283367837480',
    projectId: 'mokumokuhazard',
    storageBucket: 'mokumokuhazard.firebasestorage.app',
    iosBundleId: 'com.example.mokumouHazard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiYSFco6wLuLOiMlCI4Z8MHutKcVwbWo',
    appId: '1:283367837480:ios:5916df8ca5f499caf60a1d',
    messagingSenderId: '283367837480',
    projectId: 'mokumokuhazard',
    storageBucket: 'mokumokuhazard.firebasestorage.app',
    iosBundleId: 'com.example.mokumouHazard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqXIThmo6oHAqlDAKO2wMb9ogkLRNug1s',
    appId: '1:283367837480:web:dbd63360a118da3af60a1d',
    messagingSenderId: '283367837480',
    projectId: 'mokumokuhazard',
    authDomain: 'mokumokuhazard.firebaseapp.com',
    storageBucket: 'mokumokuhazard.firebasestorage.app',
  );
}
